spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://ujbfckjcgwymbxct:CKTAs9k7RHIAQ49p1lFZ@bcv5osrpjzmsuchc26ve-mysql.services.clever-cloud.com:3306/bcv5osrpjzmsuchc26ve?useSSL=false&serverTimezone=UTC&useLegacyDateTimeCode=false
#spring.datasource.username=ujbfckjcgwymbxct
#spring.datasource.password=CKTAs9k7RHIAQ49p1lFZ
spring.datasource.url=jdbc:mysql://localhost:3306/portfolio?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


# security
jwt.secret = miSecretillo
# media hora
jwt.expiration = 1800 
