java.runtime.version=17

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/portfolio?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root


spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# security
jwt.secret = miSecretilloSuperSecretoAntiPenetracionJodida
# media hora
jwt.expiration = 1800

spring.mvc.pathmatch.matching-strategy=ant-path-matcher

logging.level.org.springframework.security=TRACE
